### ISSUE TITLE
Error when setting up box with php7 and vanilla nginx

### ISSUE THREAD

**Issue by rskuipers** [Enrise/Basebox#21]
When I have this setup:

`pillars/default/phpfpm.sls`

``` yml
phpfpm:
  php_versions:
    - '7.0'
```

`pillars/defaults/vhosting.sls`

``` yml
vhosting:
  server:
    webserver: nginx
    webserver_edition: vanilla
```

I get the following error:

```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

salt-call state.highstate --retcode-passthrough  --log-level=info --force-color

Stdout from the command:

local:
    Data failed to compile:
----------
    Cannot extend ID 'php5-fpm' in 'base:vhosting.base'. It is not part of the high state.
This is likely due to a missing include statement or an incorrectly typed ID.
Ensure that a state with an ID of 'php5-fpm' is available
in environment 'base' and to SLS 'vhosting.base'
```

Any ideas? Let me know if I need to supply more information.
Note: This is pretty much all I have, the rest is pretty standard.
