### ISSUE TITLE
Add vhost symlink to project by default

### ISSUE THREAD

**Issue by syphernl** [Enrise/Basebox#46]
Generally, projects using the Basebox seem to be overriding the `file` state to create the web-folder and replacing it with a symlink to `/vagrant` like so:

```yaml
# Overwrite the docroot symlink of the app
extend:
  /srv/http/project/hosts/example.com:
    file.symlink:
      - target: /vagrant
      - user: vagrant
      - group: vagrant
      - require:
        - file: /srv/http/project/hosts
      - watch_in:
        - service: nginx
```

We'll probably want to add something like this to the basebox by default?
