### ISSUE TITLE
Composer fails because no php5-cli when using vanilla webserver edition

### ISSUE THREAD

**Issue by rskuipers** [Enrise/Basebox#7]
When using `webserver_edition: vanilla` it tries to install composer but php5-cli isn't installed so it fails.

**Comment by rick-nu** [comment]
I've had the same issue, fixed it with the following addition to `dev/salt/pillar/custom.sls`:

``` yaml
install-php-cli:
  pkg.installed:
    - pkgs:
      - php5-cli
    - require_in:
      - cmd: get-composer
```

Would be nice if this worked out of the box though
